version: "3"
services:
  backend:
    container_name: portfoliobackend
    restart: always
    build:
      context:  packages/backend
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    ports:
      - "5000:5000"
    links:
      - postgres
    networks:
      - postgres

  client:
    container_name: portfolioclient
    restart: always
    build:
      context: packages/client
      dockerfile: Dockerfile
      target: production
      args:
        AUTH_URL: ${AUTH_URL}
        BACKEND_URL: ${BACKEND_URL}
    env_file:
      - .env
    ports:
      - "3000:3000"
    links:
      - postgres
    networks:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
